"""
Instance Segmentation Demo — nuScenes CAM_FRONT
================================================
Runs YOLO26n-seg on a nuScenes front-camera video and saves an annotated
output video with per-instance segmentation masks overlaid.

Two-model strategy:
    This project uses two segmentation models for complementary purposes:

    1. Fine-tuned YOLO26n-seg (--model_seg):
       - Trained on nuScenes classes (car, pedestrian, barrier, etc.)
       - Detects traffic_cone and barrier (not in COCO)
       - Mask quality is approximate — labels were convex hull polygons
         from 3D box projection, not pixel-perfect annotations
       - Use when nuScenes class coverage matters

    2. Base COCO YOLO26n-seg (--model_coco = "yolo26n-seg.pt"):
       - Pixel-perfect masks on common classes (car, pedestrian, bicycle)
       - Does NOT detect traffic_cone or barrier (not in COCO 80 classes)
       - Superior visual quality for demo purposes
       - Use for visually impressive demo footage

    Production goal: fine-tune on nuScenes-panoptic labels for
    pixel-perfect masks + full nuScenes class coverage.

Why fine-tuned masks look rectangular:
    nuScenes provides 3D bounding boxes, not 2D pixel masks.
    Labels were generated by projecting 3D box corners to the image
    plane and computing the convex hull — producing trapezoid/rectangle
    shapes rather than true object outlines.
    See convert_nuscenes_seg.py for label generation details.

Usage:
    # Fine-tuned model (nuScenes classes, approximate masks)
    python segmentation_demo.py \\
        --model ./runs/yolo26n_seg_nuscenes/weights/best.pt \\
        --video ./videos/scene_00_scene-0061.mp4 \\
        --output ./solutions_output \\
        --suffix nuscenes

    # Base COCO model (pixel-perfect masks, common classes only)
    python segmentation_demo.py \\
        --model yolo26n-seg.pt \\
        --video ./videos/scene_00_scene-0061.mp4 \\
        --output ./solutions_output \\
        --suffix coco
"""

import argparse
import os
import cv2
from pathlib import Path
from ultralytics import YOLO


def parse_args():
    parser = argparse.ArgumentParser(
        description='Instance segmentation demo on nuScenes video'
    )
    parser.add_argument('--model',  required=True,
                        help='Path to seg model weights (.pt) or '
                             '"yolo26n-seg.pt" for base COCO weights')
    parser.add_argument('--video',  required=True,
                        help='Path to input video (from export_nuscenes_video.py)')
    parser.add_argument('--output', default='./solutions_output',
                        help='Output directory for annotated video')
    parser.add_argument('--suffix', default='masks',
                        help='Output filename suffix: segmentation_{suffix}.mp4')
    parser.add_argument('--conf',   type=float, default=0.25,
                        help='Detection confidence threshold')
    return parser.parse_args()


def main():
    args = parse_args()

    Path(args.output).mkdir(parents=True, exist_ok=True)
    out_path = os.path.join(args.output, f'segmentation_{args.suffix}.mp4')

    cap = cv2.VideoCapture(args.video)
    W   = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    H   = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    FPS = cap.get(cv2.CAP_PROP_FPS) or 12
    cap.release()

    print(f"Input  : {args.video}")
    print(f"Model  : {args.model}")
    print(f"Size   : {W}x{H} @ {FPS:.1f} FPS")
    print(f"Output : {out_path}")
    print()

    model = YOLO(args.model)

    cap = cv2.VideoCapture(args.video)
    out = cv2.VideoWriter(
        out_path,
        cv2.VideoWriter_fourcc(*'mp4v'),
        FPS, (W, H)
    )

    frame_count = 0
    print("Running Segmentation...")
    while cap.isOpened():
        ret, frame = cap.read()
        if not ret:
            break
        # plot() draws both bounding boxes and filled segmentation masks
        annotated = model(frame, verbose=False, conf=args.conf)[0].plot()
        out.write(annotated)
        frame_count += 1

    cap.release()
    out.release()

    size_kb = Path(out_path).stat().st_size / 1024
    print(f"✅ Done — {frame_count} frames → {out_path} ({size_kb:.0f} KB)")


if __name__ == '__main__':
    main()